version: '3'
services:
  edwork-postgres:
    container_name: edwork-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - edwork-postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - edwork-api-go
    restart: unless-stopped
volumes:
  edwork-postgres-data:
networks:
  edwork-api-go:
    driver: bridge
