package utils

var (
	GENDER_MALE = "MALE"
	GENDER_FEMALE = "FEMALE"
	GENDER_OTHER = "OTHER"
)

var (
	OWNER_TYPE_STUDENT = "STUDENT"
	OWNER_TYPE_PARENT = "PARENT"
	OWNER_TYPE_TEACHER = "TEACHER"
	OWNER_TYPE_OTHER = "OTHER"
)

var (
	SIGN_UP_PROVIDER_EMAIL = "EMAIL"
	SIGN_UP_PROVIDER_FACEBOOK = "FACEBOOK"
	SIGN_UP_PROVIDER_GOOGLE = "GOOGLE"
	SIGN_UP_PROVIDER_APPLE = "APPLE"
)